# Generated by Django 5.1.1 on 2024-09-05 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('isbn_13', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)])),
                ('isbn_10', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('published_date', models.DateField()),
                ('pages', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('rating_star', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('rating_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('author', models.CharField(max_length=50)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('review_list', models.JSONField(default=dict)),
            ],
        ),
    ]
