# Generated by Django 5.1.1 on 2024-09-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookentry_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookentry',
            name='image',
            field=models.ImageField(default='books/default.jpg', upload_to='books/'),
        ),
    ]
