# Generated by Django 5.1.1 on 2024-09-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bookentry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookentry',
            name='image',
            field=models.ImageField(default='books/default.jpeg', upload_to='books/'),
        ),
    ]
