# Generated by Django 5.1.1 on 2024-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_bookentry_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/books/'),
        ),
    ]
